# Generated by Django 3.2 on 2021-04-27 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_post_categoris'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categoris',
            new_name='categorias',
        ),
    ]
