# Generated by Django 3.2 on 2021-04-27 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_rename_approved_post_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categorias',
            new_name='categories',
        ),
    ]
